//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM._01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jure
    {
        public int ID { get; set; }
        public string Mail { get; set; }
        public System.DateTime Birthday { get; set; }
        public int Country_ID { get; set; }
        public string Phone { get; set; }
        public string Direct { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
